INSERT INTO SAMPLE VALUES(1,'Runtime Environment','Foundation Layer','Y','eGov');
INSERT INTO SAMPLE VALUES(2,'Runtime Environment','Persistence Layer','Y','eGov');
INSERT INTO SAMPLE VALUES(3,'Runtime Environment','Presentation Layer','Y','eGov');
INSERT INTO SAMPLE VALUES(4,'Runtime Environment','Business Layer','Y','eGov');
INSERT INTO SAMPLE VALUES(5,'Runtime Environment','Batch Layer','Y','eGov');
INSERT INTO SAMPLE VALUES(6,'Runtime Environment','Integration Layer','Y','eGov');
INSERT INTO SAMPLE VALUES(7,'Runtime Environment','Integration Layer','Y','eGov');
INSERT INTO SAMPLE VALUES(8,'Runtime Environment','Integration Layer','Y','eGov');
INSERT INTO SAMPLE VALUES(9,'Runtime Environment','Integration Layer','Y','eGov');
INSERT INTO SAMPLE VALUES(10,'Runtime Environment','Integration Layer','Y','eGov');
INSERT INTO IDS VALUES('SAMPLE',115);