DROP TABLE SAMPLE IF EXISTS ;
DROP TABLE IDS IF EXISTS ;
DROP TABLE NEXA_SAMPLE IF EXISTS ;
DROP SEQUENCE SEQ_ID IF EXISTS ;
CREATE TABLE SAMPLE (
    ID INTEGER(10) NOT NULL PRIMARY KEY,
    NAME VARCHAR(50),
    DESCRIPTION VARCHAR(100),
    USE_YN CHAR(1),
    REG_USER VARCHAR(10)
);
CREATE TABLE IDS(
    TABLE_NAME VARCHAR(16) NOT NULL PRIMARY KEY,
    NEXT_ID DECIMAL(30) NOT NULL
);
CREATE SEQUENCE SEQ_ID
	START WITH 11
	INCREMENT BY 1;
	
CREATE TABLE NEXA_SAMPLE(
	SYS_CD VARCHAR(50) NOT NULL,
	MOD_ID VARCHAR(50) PRIMARY KEY,
	MOD_NM VARCHAR(50),
	MOD_TY VARCHAR(50),
	MOD_GCD VARCHAR(50),
	CLA_NM VARCHAR(50),
	USE_YN VARCHAR(50),
	DES2 VARCHAR(50),
	DUT_L VARCHAR(50),
	DUT_M VARCHAR(50),
	DUT_S VARCHAR(50),
	INQ_YN VARCHAR(50),
	RG_YN VARCHAR(50),
	DEL_YN VARCHAR(50),
	PRT_YN VARCHAR(50),
	EXL_YN VARCHAR(50),
	CON_YN VARCHAR(50),
	ERNAM VARCHAR(50),
	ERNAMT VARCHAR(50),
	ERDAT VARCHAR(50),
	AENAM VARCHAR(50),
	AENAMT VARCHAR(50),
	AEDAT VARCHAR(50),
	MESSAGE VARCHAR(50)
);
	