DROP TABLE SAMPLE IF EXISTS ;
DROP TABLE IDS IF EXISTS ;
CREATE TABLE SAMPLE (
    ID INTEGER(10) NOT NULL PRIMARY KEY,
    NAME VARCHAR(50),
    DESCRIPTION VARCHAR(100),
    USE_YN CHAR(1),
    REG_USER VARCHAR(10)
);
CREATE TABLE IDS(
    TABLE_NAME VARCHAR(16) NOT NULL PRIMARY KEY,
    NEXT_ID DECIMAL(30) NOT NULL
);
